config/routes.rb
SassyHash::Application.routes.draw do
root :to => 'static#home'

match 'about' => 'static#about'
match 'contact' => 'static#contact'
match 'work' => 'static#work'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/static_controller.rb
class StaticController < ApplicationController

  def contact 
  end

  def about
  end

  def work
  end

  def home
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-40080208-1']);
  _gaq.push(['_setDomainName', 'sassyha.sh']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

  </script>

  <meta name="google-site-verification" content="DvfPkdaWryOQDHSNe9gXCNTwDx8sdKq5g7v1Et3fzTg" />

  <title>SassyHash</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <header class="navbar navbar-inverse">
    <div class="navbar-inner">

      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>

      <a class="brand" href="#">Sassy Hash</a>
      
      <div class="nav-collapse collapse">
        <ul class="nav">
          <li class="dropdown">
            <%= link_to "B", about_path %>
          </li>
        </ul>

        <ul class="nav pull-right" >
          <li class="navbar-text"> <%= link_to "My Work", work_path %> </li>
          <li class="navbar-text" style="color: #f4c2c2"> <%= link_to "Contact B", contact_path %> </li>
        </ul>
      </div>
    </div>
  </header>
<%= yield %>


<footer>
    <div class="footer-stuff">
      &copy; {Sassy Hash} 2013
    </div>
</footer>
</body>
</html>